// Tabelas de vendas do Consumer (espelho): Produto, Pedido, PedidoItem.
import {
  pgTable,
  uuid,
  text,
  timestamp,
  varchar,
  integer,
  numeric,
  boolean,
  index,
  unique,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { filial } from './tenant';

/** Produto (espelha PRODUTOS do Consumer). */
export const produto = pgTable(
  'produto',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    filialId: uuid('filial_id').notNull().references(() => filial.id, { onDelete: 'cascade' }),
    codigoExterno: integer('codigo_externo').notNull(),
    nome: varchar('nome', { length: 200 }),
    descricao: text('descricao'),
    codigoPersonalizado: varchar('codigo_personalizado', { length: 50 }),
    codigoEtiqueta: varchar('codigo_etiqueta', { length: 50 }),
    precoVenda: numeric('preco_venda', { precision: 14, scale: 4 }),
    precoCusto: numeric('preco_custo', { precision: 14, scale: 4 }),
    estoqueAtual: numeric('estoque_atual', { precision: 14, scale: 3 }),
    estoqueMinimo: numeric('estoque_minimo', { precision: 14, scale: 3 }),
    estoqueControlado: boolean('estoque_controlado'),
    descontinuado: boolean('descontinuado'),
    itemPorKg: boolean('item_por_kg'),
    codigoUnidadeComercial: integer('codigo_unidade_comercial'),
    codigoProdutoTipo: integer('codigo_produto_tipo'),
    codigoCozinha: integer('codigo_cozinha'),
    ncm: varchar('ncm', { length: 10 }),
    cfop: varchar('cfop', { length: 10 }),
    cest: varchar('cest', { length: 10 }),
    versaoReg: integer('versao_reg'),
    sincronizadoEm: timestamp('sincronizado_em', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    uniqCodigo: unique('uq_produto_filial_codigo').on(t.filialId, t.codigoExterno),
    nomeIdx: index('idx_produto_nome').on(t.filialId, t.nome),
  }),
);

/** Pedido/Venda (cabecalho). Espelha PEDIDOS. */
export const pedido = pgTable(
  'pedido',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    filialId: uuid('filial_id').notNull().references(() => filial.id, { onDelete: 'cascade' }),
    codigoExterno: integer('codigo_externo').notNull(),
    numero: integer('numero'),
    senha: varchar('senha', { length: 30 }),
    codigoClienteContatoExterno: integer('codigo_cliente_contato_externo'),
    codigoClienteFiadoExterno: integer('codigo_cliente_fiado_externo'),
    nomeCliente: varchar('nome_cliente', { length: 200 }),
    codigoColaborador: integer('codigo_colaborador'),
    codigoUsuarioCriador: integer('codigo_usuario_criador'),
    dataAbertura: timestamp('data_abertura', { withTimezone: true }),
    dataFechamento: timestamp('data_fechamento', { withTimezone: true }),
    valorTotal: numeric('valor_total', { precision: 14, scale: 2 }),
    valorTotalItens: numeric('valor_total_itens', { precision: 14, scale: 2 }),
    subtotalPago: numeric('subtotal_pago', { precision: 14, scale: 2 }),
    totalDesconto: numeric('total_desconto', { precision: 14, scale: 2 }),
    percentualDesconto: numeric('percentual_desconto', { precision: 8, scale: 4 }),
    totalAcrescimo: numeric('total_acrescimo', { precision: 14, scale: 2 }),
    totalServico: numeric('total_servico', { precision: 14, scale: 2 }),
    percentualTaxaServico: numeric('percentual_taxa_servico', { precision: 8, scale: 4 }),
    valorEntrega: numeric('valor_entrega', { precision: 14, scale: 2 }),
    valorTroco: numeric('valor_troco', { precision: 14, scale: 2 }),
    valorIva: numeric('valor_iva', { precision: 14, scale: 2 }),
    quantidadePessoas: integer('quantidade_pessoas'),
    notaEmitida: boolean('nota_emitida'),
    tag: varchar('tag', { length: 100 }),
    codigoPedidoOrigem: integer('codigo_pedido_origem'),
    codigoCupom: integer('codigo_cupom'),
    dataDelete: timestamp('data_delete', { withTimezone: true }),
    versaoReg: integer('versao_reg'),
    sincronizadoEm: timestamp('sincronizado_em', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    uniqCodigo: unique('uq_pedido_filial_codigo').on(t.filialId, t.codigoExterno),
    dataIdx: index('idx_pedido_data').on(t.filialId, t.dataFechamento),
    clienteIdx: index('idx_pedido_cliente').on(t.filialId, t.codigoClienteContatoExterno),
  }),
);

/** Item do pedido (espelha ITENSPEDIDO). */
export const pedidoItem = pgTable(
  'pedido_item',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    filialId: uuid('filial_id').notNull().references(() => filial.id, { onDelete: 'cascade' }),
    codigoExterno: integer('codigo_externo').notNull(),
    codigoPedidoExterno: integer('codigo_pedido_externo').notNull(),
    codigoProdutoExterno: integer('codigo_produto_externo'),
    pedidoId: uuid('pedido_id').references(() => pedido.id, { onDelete: 'cascade' }),
    produtoId: uuid('produto_id').references(() => produto.id, { onDelete: 'set null' }),
    nomeProduto: varchar('nome_produto', { length: 200 }),
    quantidade: numeric('quantidade', { precision: 14, scale: 3 }),
    valorUnitario: numeric('valor_unitario', { precision: 14, scale: 4 }),
    precoCusto: numeric('preco_custo', { precision: 14, scale: 4 }),
    valorItem: numeric('valor_item', { precision: 14, scale: 2 }),
    valorComplemento: numeric('valor_complemento', { precision: 14, scale: 2 }),
    valorFilho: numeric('valor_filho', { precision: 14, scale: 2 }),
    valorDesconto: numeric('valor_desconto', { precision: 14, scale: 2 }),
    valorGorjeta: numeric('valor_gorjeta', { precision: 14, scale: 2 }),
    valorTotal: numeric('valor_total', { precision: 14, scale: 2 }),
    codigoPai: integer('codigo_pai'),
    codigoItemPedidoTipo: integer('codigo_item_pedido_tipo'),
    codigoPagamento: integer('codigo_pagamento'),
    codigoColaborador: integer('codigo_colaborador'),
    dataHoraCadastro: timestamp('data_hora_cadastro', { withTimezone: true }),
    dataDelete: timestamp('data_delete', { withTimezone: true }),
    detalhes: text('detalhes'),
    versaoReg: integer('versao_reg'),
    sincronizadoEm: timestamp('sincronizado_em', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    uniqCodigo: unique('uq_pedido_item_filial_codigo').on(t.filialId, t.codigoExterno),
    pedidoIdx: index('idx_pedido_item_pedido').on(t.filialId, t.codigoPedidoExterno),
    produtoIdx: index('idx_pedido_item_produto').on(t.filialId, t.codigoProdutoExterno),
  }),
);
