{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cielo.lio",
    "module": "order-manager",
    "version": "2.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "order-manager-2.5.5.aar",
          "url": "order-manager-2.5.5.aar",
          "size": 266171,
          "sha512": "dc33a1ae510307b4276c2b25ba17d43a9e3ce609bdc5aab429b9cd0a1a25e418fd46c117bdb69712a6ae0d9b178741b891494a86808a1704252206cdebccc2a6",
          "sha256": "78b829b8456a62db6858d4a6429bd29011688f941e3e56000fbc8b1ff6a18e69",
          "sha1": "63929fe9b1d946eeeacdbd8407f67630bc3930ea",
          "md5": "9e3559db9a475251d3e44a4485e37799"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "cielo.smart",
          "module": "event-tracker",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "order-manager-2.5.5.aar",
          "url": "order-manager-2.5.5.aar",
          "size": 266171,
          "sha512": "dc33a1ae510307b4276c2b25ba17d43a9e3ce609bdc5aab429b9cd0a1a25e418fd46c117bdb69712a6ae0d9b178741b891494a86808a1704252206cdebccc2a6",
          "sha256": "78b829b8456a62db6858d4a6429bd29011688f941e3e56000fbc8b1ff6a18e69",
          "sha1": "63929fe9b1d946eeeacdbd8407f67630bc3930ea",
          "md5": "9e3559db9a475251d3e44a4485e37799"
        }
      ]
    }
  ]
}
